name: tests for lifebit-ai/simulate
# This workflow is triggered on pushes and PRs to the repository.
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nxf_ver: ['20.01.0', '']
        gwas_pheno_trait_type: ['binary', 'quantitative']
    steps:
      - uses: actions/checkout@v1
      - name: Install Nextflow
        run: |
          export NXF_VER=${{ matrix.nxf_ver }}
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: test
        run: |
          nextflow run ${GITHUB_WORKSPACE} --gwas_pheno_trait_type ${{ matrix.gwas_pheno_trait_type }}  -profile test
  simple_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gwas_pheno_trait_type: ['binary', 'quantitative']
    steps:
      - uses: actions/checkout@v1
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Run script
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test

          